alias ll="ls -lah"
alias lS="ls -lahS"
alias draw_crtc="luajit /usr/share/lua/5.1/libdrm/examples/draw_crtc.lua"
alias drm_info="luajit /usr/share/lua/5.1/libdrm/examples/info.lua"
alias drm_test="luajit /usr/share/lua/5.1/libdrm/examples/test.lua"
